### ISSUE TITLE
Not() for parse_comparisons

### ISSUE THREAD

**Issue by sallyrobson** [e4st-dev/E4ST.jl#227]
It would sometimes be helpful to be able to make a filter that is saying "everything except this" like the `Not()` function. It isn't crucial but it would make some things cleaner. Particularly thinking about CreditingByBenchmark and how you could say to not include fossil generation instead of listing all the non fossil generation to include.

**Comment by Ethan-Russell** [comment]
I think you could do this via "!=(coal)". But I assume you would want it to
be able to work for multiple things, so the "Not" syntax might be a better
choice

**Comment by Ethan-Russell** [comment]
On further thought, I think a cleaner way to do this would be something like:
```
![coal, ng]
```
This matches our syntax.  Then under the hood we can use the function `!in` to match what we do for when an array is given as an argument.  @sallyrobson would you like me to do this or would you like to?
