### ISSUE TITLE
Missing data in AggregationTemplate output

### ISSUE THREAD

**Issue by sallyrobson** [e4st-dev/E4ST.jl#276]
Sometimes AggregationTemplate doesn't calculate things that it should. The current example was from a results template with the line
`bus, electricity_price, is_dac=>1` where `is_dac` is a column that is added to the bus table using `LeftJoinCols`. After reading in the processed results, I am able to use is_dac as a filter in `compute_result()` so I know it still exists in the bus table. We should figure out why it isn't calculating in AggregationTemplate

**Comment by Ethan-Russell** [comment]
This should be fixed in #280
